data(iris)
model <- lm(Petal.Length ~ Petal.Width, data = iris)
summary(model)
plot(iris$Petal.Width, iris$Petal.Length)
abline(model, col="red")
new_data<-data.frame(Petal.Width=1.5)
pred<-predict(model,new_data)
cat("The predicted output of new petal length is ",pred)
